eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery:8761/eureka

server:
  port: 8222

spring:
  application:
    name: gateway
management:
  tracing:
    sampling:
      probability: 1.0
  cloud:
    gateway:
      routes:
        - id: students
          uri: lb://STUDENTS
          predicates:
            - Path=/api/v1/students/**
        - id: schools
          uri: lb://SCHOOLS
          predicates:
            - Path=/api/v1/school/**
    locator:
      enabled: true
      lower-case-service-id: true
    discovery:
      locator:
        enabled: true
