eureka:
  client:
    fetch-registry: false
    service-url:
      defaultZone: http://discovery-service:8761/eureka

server:
  port: 8222

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: students
          uri: lb://student-service
          predicates:
            - Path=/api/v1/students/**
        - id: schools
          uri: http://school-service:8070
          predicates:
            - Path=/api/v1/school/**
    locator:
      enabled: true
      lower-case-service-id: true
    discovery:
      locator:
        enable: true
