# add eureka configuration
eureka:
  instance:
    hostname: students #because we have given localhost to Discovery project
    prefer-ip-address: false
    instance-id: students:${server.port}
  client: #A Eureka client (your microservice student) needs to register itself with the Eureka Server to be discoverable by other services.
    service-url:
      defaultZone: http://discovery:8761/eureka

server:
  port: 8090

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans

spring:
  application:
    name: students
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://mysql-db:3306/student_microservice?characterEncoding=UTF-8
    username: root
    password: test
  jpa:
    hibernate:
      ddl-auto: create
